# -*- coding: utf-8 -*-
"""CV Lab 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGU1Na0A3-Dq4XHMnVvKtwG5uzL7Qjma
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

def show_comparitions(original, sobel, prewitt, canny):
  plt.figure(figsize=(12,10))
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title('Original gray scale image')

  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title('Sobel edge detection')

  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title('Prewitt edge detection')

  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title('Canny edge detection')

  plt.tight_layout()
  plt.show()


img = cv2.imread('/content/strawberry.jpg', cv2.IMREAD_GRAYSCALE)

if img is None:
  print('Error: Could not load image.')
else:

  sobelx = cv2.Sobel(img, cv2.CV_64F, 1, 0, ksize=3)
  sobely = cv2.Sobel(img, cv2.CV_64F, 0, 1, ksize=3)
  sobel_combined = cv2.magnitude(sobelx, sobely)
  sobel_result = cv2.normalize(sobel_combined, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

  kernelx = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
  kernely = np.array([[-1, -1, -1], [0, 0, 0], [1, 1, 1]])

  prewittx = cv2.filter2D(img, cv2.CV_64F, kernelx)
  prewitty = cv2.filter2D(img, cv2.CV_64F, kernely)
  prewitt_combined = cv2.magnitude(prewittx, prewitty)
  prewitt_result = cv2.normalize(prewitt_combined, None, 0, 255, cv2.NORM_MINMAX, cv2.CV_8U)

  canny_edges = cv2.Canny(img, 100, 200)

  show_comparitions(img, sobel_result, prewitt_result, canny_edges)