# -*- coding: utf-8 -*-
"""CV LAB - 06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQGd0blRcBUAxKVAPo7zj1E5Bx3qSjnw
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img = cv2.imread('input_image.jpg',cv2.IMREAD_GRAYSCALE)
img = cv2.imread('/content/drive/MyDrive/cvimage1.jpg')
if img is None:
  print("Error:image not found.")
else:
    plt.figure(figsize=(12,10))
    plt.subplot(3,3,1)
    plt.imshow(img,cmap='gray')
    plt.title('Original Image')
    plt.axis('off')
for i in range(8):
  bit_plane = (img>>i)&1
  vis_plane=bit_plane*255
  plt.subplot(3,3,i+2)
  plt.imshow(vis_plane,cmap='gray')
  plt.title(f'Bit Plane {i}')
  plt.axis('off')
  plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import cv2

def filtered_image(img , kernel , p , s):
  rows = (img.shape[0] - kernel.shape[0] + 2 * p ) // s + 1
  cols = (img.shape[1] - kernel.shape[1] + 2 * p ) // s + 1

  output = np.zeros((rows,cols))

  if p == 0:
    padded_img = img
  else:
    padded_img = np.pad(img,p,constant_values=0)

  for i in range(rows):
      for j in range(cols):
          output[i][j] = np.sum(
                padded_img[
                    i * s : i * s + kernel.shape[0],
                    j * s : j * s + kernel.shape[1]
                ] * kernel
            )




  return output

k = 15

img = cv2.imread("/content/drive/MyDrive/Computer Vision/pngtree-new-4k-nature-cb-editing-background-image_16123064.jpg", 0)

kernel = np.ones((k, k)) / k**2

filtered_img = filtered_image(img,kernel,p=1,s=2)

plt.imshow(filtered_img,cmap="gray")
plt.title("Implementation of 2D Image Filtering using a Mean Filter with Padding and Stride")
plt.axis("off")
plt.show()

import numpy as np
import cv2
import matplotlib.pyplot as plt


def filtered_image(img, kernel, p, s):
    rows = (img.shape[0] - kernel.shape[0] + 2 * p) // s + 1
    cols = (img.shape[1] - kernel.shape[1] + 2 * p) // s + 1

    output = np.zeros((rows, cols))

    if p == 0:
        padded_img = img
    else:
        padded_img = np.pad(img, p, constant_values=0)

    for i in range(rows):
        for j in range(cols):

            output[i][j] = np.sum(
                padded_img[
                    i * s : i * s + kernel.shape[0],
                    j * s : j * s + kernel.shape[1]
                ] * kernel
            )

    return output



img = cv2.imread("/content/drive/MyDrive/Computer Vision/pngtree-new-4k-nature-cb-editing-background-image_16123064.jpg", 0)




k = 15

mean_kernel = np.ones((k, k)) / k**2

mean_img = filtered_image(
    img,
    mean_kernel,
    p=1,
    s=2
)




gaussian_1d = cv2.getGaussianKernel(k, 0)

gaussian_kernel = gaussian_1d @ gaussian_1d.T

gaussian_img = filtered_image(
    img,
    gaussian_kernel,
    p=1,
    s=2
)




sobel_x = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

gradient_x = filtered_image(
    img,
    sobel_x,
    p=1,
    s=1
)




sobel_y = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
])

gradient_y = filtered_image(
    img,
    sobel_y,
    p=1,
    s=1
)




gradient = np.sqrt(
    gradient_x**2 + gradient_y**2
)





plt.figure(figsize=(12, 8))

plt.subplot(2, 3, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(2, 3, 2)
plt.imshow(mean_img, cmap="gray")
plt.title("Mean Smoothing")
plt.axis("off")

plt.subplot(2, 3, 3)
plt.imshow(gaussian_img, cmap="gray")
plt.title("Gaussian Smoothing")
plt.axis("off")

plt.subplot(2, 3, 4)
plt.imshow(gradient_x, cmap="gray")
plt.title("Sobel X Gradient")
plt.axis("off")

plt.subplot(2, 3, 5)
plt.imshow(gradient_y, cmap="gray")
plt.title("Sobel Y Gradient")
plt.axis("off")

plt.subplot(2, 3, 6)
plt.imshow(gradient, cmap="gray")
plt.title("Gradient Magnitude")
plt.axis("off")

plt.show()

import numpy as np
import cv2
import matplotlib.pyplot as plt


def filtered_image(img, kernel, p, s):
    rows = (img.shape[0] - kernel.shape[0] + 2 * p) // s + 1
    cols = (img.shape[1] - kernel.shape[1] + 2 * p) // s + 1

    output = np.zeros((rows, cols))

    if p == 0:
        padded_img = img
    else:
        padded_img = np.pad(img, p, constant_values=0)

    for i in range(rows):
        for j in range(cols):
            output[i][j] = np.sum(
                padded_img[
                    i * s : i * s + kernel.shape[0],
                    j * s : j * s + kernel.shape[1]
                ] * kernel
            )

    return output


img = cv2.imread("/content/drive/MyDrive/Computer Vision/pngtree-new-4k-nature-cb-editing-background-image_16123064.jpg", 0)

k = 15

mean_kernel = np.ones((k, k)) / k**2

mean_img = filtered_image(
    img,
    mean_kernel,
    p=1,
    s=2
)

gaussian_1d = cv2.getGaussianKernel(k, 0)
gaussian_kernel = gaussian_1d @ gaussian_1d.T

gaussian_img = filtered_image(
    img,
    gaussian_kernel,
    p=1,
    s=2
)

sobel_x = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

gradient_x = filtered_image(
    gaussian_img,
    sobel_x,
    p=1,
    s=1
)

sobel_y = np.array([
    [-1, -2, -1],
    [0, 0, 0],
    [1, 2, 1]
])

gradient_y = filtered_image(
    gaussian_img,
    sobel_y,
    p=1,
    s=1
)

gradient = np.sqrt(
    gradient_x**2 + gradient_y**2
)

angle_img = np.degrees(
    np.arctan2(gradient_y, gradient_x)
)

angle_img = angle_img % 180

rows, cols = angle_img.shape

quantized_angle = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):

        angle_value = angle_img[i][j]

        if 0 <= angle_value <= 22.5:
            quantized_angle[i][j] = 0

        elif 22.5 < angle_value <= 67.5:
            quantized_angle[i][j] = 45

        elif 67.5 < angle_value <= 112.5:
            quantized_angle[i][j] = 90

        elif 112.5 < angle_value <= 157.5:
            quantized_angle[i][j] = 135

        elif 157.5 < angle_value < 180:
            quantized_angle[i][j] = 0


plt.figure(figsize=(12, 10))

plt.subplot(2, 4, 1)
plt.imshow(img, cmap="gray")
plt.title("Original Image")
plt.axis("off")

plt.subplot(2, 4, 2)
plt.imshow(mean_img, cmap="gray")
plt.title("Mean Smoothing")
plt.axis("off")

plt.subplot(2, 4, 3)
plt.imshow(gaussian_img, cmap="gray")
plt.title("Gaussian Smoothing")
plt.axis("off")

plt.subplot(2, 4, 4)
plt.imshow(gradient_x, cmap="gray")
plt.title("Sobel X")
plt.axis("off")

plt.subplot(2, 4, 5)
plt.imshow(gradient_y, cmap="gray")
plt.title("Sobel Y")
plt.axis("off")

plt.subplot(2, 4, 6)
plt.imshow(gradient, cmap="gray")
plt.title("Gradient Magnitude")
plt.axis("off")

plt.subplot(2, 4, 7)
plt.imshow(angle_img, cmap="gray")
plt.title("Gradient Orientation")
plt.axis("off")

plt.subplot(2, 4, 8)
plt.imshow(quantized_angle, cmap="gray")
plt.title("Quantized Orientation")
plt.axis("off")

plt.show()

for i in range(rows):
    for j in range(cols):
        angle_value = angle_img[i][j]

        if 0 <= angle_value <= 22.5:
            angle_img[i][j] = 0

        elif 22.5 < angle_value <= 67.5:
            angle_img[i][j] = 45

        elif 67.5 < angle_vlaue <= 115.5:
            angle_img[i][j] = 90


for i in range(1,quantized_angle):
    for j in range(1,quantized_angle):
        angle_value[i][j] = quantized_angle[i][j]